# Project Euler ID #2

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

fib_seq = [1]
new_max = 2
while new_max < 4000000:
    fib_seq.append(new_max)
    new_max = fib_seq[-2] + fib_seq[-1]
print "fib_seq:" 
print fib_seq
print "max fib_seq: "
print max(fib_seq)
print "sum fib_seq: "
print sum(fib_seq)


print "sum even fib_seq:"
fib_sum = 0 
for i in fib_seq:
    if i%2==0:
        fib_sum += i
print fib_sum
